export EH_Sender = "kyle.astudillo@yahoo.com"
export EH_Recipient = "kyle.astudillo@yahoo.com"
export EH_Subject = "Amazon SES Test (AWS SDK for Go)"
export EH_HtmlBody =  "<h1>Amazon SES Test Email (AWS SDK for Go)</h1><p>This email was sent with<a href='https://aws.amazon.com/ses/'>Amazon SES</a> using the <a href='https://aws.amazon.com/sdk-for-go/'>AWS SDK for Go</a>.</p>"
export EH_TextBody = "This email was sent with Amazon SES using the AWS SDK for Go."
